version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.34
    - 14.14.36
    - 14.14.41
    - 15.0.0
  - dependency-name: next-pwa
    versions:
    - 5.1.4
    - 5.2.1
    - 5.2.14
    - 5.2.3
    - 5.2.5
  - dependency-name: styled-components
    versions:
    - 5.2.2
  - dependency-name: next
    versions:
    - 10.1.1
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.0
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
